import test from 'node:test';
import assert from 'node:assert/strict';
import { REACTIONS, MODEL_NOTE, parseMoles, solveReaction, formatMoles, outcomeText, workedRecord } from '../src/stoichiometry.mjs';

const close = (actual, expected, label = '') => assert.ok(
  Math.abs(actual - expected) <= 1e-11 * Math.max(1, Math.abs(expected)),
  `${label}: expected ${expected}, received ${actual}`
);

// Values below are worked chemistry oracles, not generated by solveReaction.
const examples = [
  ['water', ['6', '2'], 'second', 2, 4, [2, 0]],
  ['water', ['2', '2'], 'first', 1, 2, [0, 1]],
  ['water', ['4', '2'], 'matched', 2, 4, [0, 0]],
  ['water', ['0', '5'], 'no-product', 0, 0, [0, 5]],
  ['water', ['5', '0'], 'no-product', 0, 0, [5, 0]],
  ['water', ['0', '0'], 'no-product', 0, 0, [0, 0]],
  ['ammonia', ['2', '3'], 'second', 1, 2, [1, 0]],
  ['ammonia', ['1', '2.4'], 'second', 0.8, 1.6, [0.2, 0]],
  ['ammonia', ['2', '4.8'], 'second', 1.6, 3.2, [0.4, 0]],
  ['ammonia', ['0.1', '0.3'], 'matched', 0.1, 0.2, [0, 0]],
  ['ammonia', ['0.001', '0.001'], 'second', 1 / 3000, 2 / 3000, [2 / 3000, 0]],
  ['ammonia', ['0.001', '0.003'], 'matched', 0.001, 0.002, [0, 0]],
  ['ammonia', ['0.001', '0.004'], 'first', 0.001, 0.002, [0, 0.001]],
  ['magnesium', ['1.5', '1'], 'first', 0.75, 1.5, [0, 0.25]],
  ['magnesium', ['1', '0.499'], 'second', 0.499, 0.998, [0.002, 0]],
  ['magnesium', ['1', '0.5'], 'matched', 0.5, 1, [0, 0]],
  ['magnesium', ['1', '0.501'], 'first', 0.5, 1, [0, 0.001]],
  ['water', ['1000', '1000'], 'first', 500, 1000, [0, 500]]
];
for (const [reaction, inputs, classification, extent, product, left] of examples) {
  test(`${reaction}: ${inputs.join(' / ')} mol → ${classification}`, () => {
    const result = solveReaction(reaction, inputs);
    assert.equal(result.classification, classification);
    close(result.extent, extent, 'extent');
    close(result.products[0].formed, product, 'product');
    result.reactants.forEach((item, index) => close(item.remaining, left[index], `left ${index}`));
  });
}

test('authored equations use the declared species and conserve each element', () => {
  assert.deepEqual(REACTIONS.map(row => [row.id, row.reactants.map(item => [item.formula, item.coefficient]), row.products.map(item => [item.formula, item.coefficient])]), [
    ['water', [['H₂', 2], ['O₂', 1]], [['H₂O', 2]]],
    ['ammonia', [['N₂', 1], ['H₂', 3]], [['NH₃', 2]]],
    ['magnesium', [['Mg', 2], ['O₂', 1]], [['MgO', 2]]]
  ]);
  const atoms = items => items.reduce((total, item) => {
    for (const [element, count] of Object.entries(item.atoms)) total[element] = (total[element] ?? 0) + count * item.coefficient;
    return total;
  }, {});
  for (const reaction of REACTIONS) assert.deepEqual(atoms(reaction.reactants), atoms(reaction.products), reaction.id);
});

test('all admitted decimal spellings resolve to exact millimoles', () => {
  for (const [text, expected] of [['0', 0], ['.001', 1], ['0.010', 10], ['0002.400', 2400], [' 2.4 ', 2400], ['1000.000', 1000000]]) {
    assert.equal(parseMoles(text), expected);
  }
});

test('invalid or ambiguous amount inputs are refused without numeric coercion', () => {
  for (const value of ['', ' ', '-1', '-0', '1e2', 'Infinity', 'NaN', '0x10', '1,5', '1 mol', '+2', '1 2', '0.0001', '1000.001', '1001', '9'.repeat(33), null, undefined, 1, true, {}, []]) {
    assert.throws(() => parseMoles(value), Error, String(value));
  }
  for (const amounts of [null, {}, [], ['1'], ['1', '2', '3'], new Array(2), ['1', undefined]]) {
    assert.throws(() => solveReaction('water', amounts), Error);
  }
  assert.throws(() => solveReaction('custom-unbalanced', ['1', '1']), /authored balanced/);
});

test('positive amounts straddling an exact ratio are never classified using a floating tolerance', () => {
  assert.equal(solveReaction('ammonia', ['100', '299.999']).classification, 'second');
  assert.equal(solveReaction('ammonia', ['100', '300']).classification, 'matched');
  assert.equal(solveReaction('ammonia', ['100', '300.001']).classification, 'first');
});

test('start = used + left and atom inventory is conserved across a changed-input grid', () => {
  const values = ['0', '0.001', '0.003', '0.017', '0.125', '1', '2.4', '499.999', '1000'];
  for (const reaction of REACTIONS) {
    for (const first of values) for (const second of values) {
      const result = solveReaction(reaction.id, [first, second]);
      const before = {}, after = {};
      for (const item of result.reactants) {
        assert.ok(item.remaining >= 0 && item.consumed >= 0);
        close(item.initial, item.consumed + item.remaining, 'reactant inventory');
        for (const [element, count] of Object.entries(item.atoms)) {
          before[element] = (before[element] ?? 0) + count * item.initial;
          after[element] = (after[element] ?? 0) + count * item.remaining;
        }
      }
      for (const item of result.products) for (const [element, count] of Object.entries(item.atoms)) {
        after[element] = (after[element] ?? 0) + count * item.formed;
      }
      for (const element of Object.keys(before)) close(after[element], before[element], `${reaction.id} ${first}/${second} ${element}`);
      assert.ok(result.reactants.some(item => item.remaining === 0), 'completion exhausts at least one required supply');
    }
  }
});

test('doubling both supplies doubles theoretical product and excess without changing the limiting identity', () => {
  for (const reaction of REACTIONS) {
    for (const amounts of [[1, 1], [1, 3], [2, 3], [0, 7], [3, 0]]) {
      const original = solveReaction(reaction.id, amounts.map(String));
      const doubled = solveReaction(reaction.id, amounts.map(value => String(2 * value)));
      assert.equal(doubled.classification, original.classification);
      close(doubled.products[0].formed, 2 * original.products[0].formed);
      doubled.reactants.forEach((item, index) => close(item.remaining, 2 * original.reactants[index].remaining));
    }
  }
  const before = solveReaction('water', ['2', '2']);
  const moreExcess = solveReaction('water', ['2', '4']);
  assert.equal(moreExcess.products[0].formed, before.products[0].formed);
  assert.equal(moreExcess.reactants[1].remaining, before.reactants[1].remaining + 2);
});

test('reaction definitions and solved records are deeply immutable without changing caller inputs', () => {
  const inputs = [' 2 ', '3'];
  const result = solveReaction('ammonia', inputs);
  assert.deepEqual(inputs, [' 2 ', '3']);
  assert.deepEqual(result.inputs, ['2', '3']);
  assert.throws(() => { result.reactants[0].remaining = 99; }, TypeError);
  assert.throws(() => { result.reaction.reactants[0].atoms.N = 99; }, TypeError);
  assert.throws(() => { result.inputs.push('4'); }, TypeError);
});

test('worked record carries this prediction, mole accounting and the explicit theoretical model', () => {
  const result = solveReaction('ammonia', ['2', '3']);
  const record = workedRecord(result, 'second');
  for (const text of ['N₂ + 3 H₂ → 2 NH₃', 'Hydrogen limits', 'Shared extent = the smaller capacity = 1 mol', 'Theoretical NH₃: 2 × 1 = 2 mol', 'N₂: 2 mol initially; 1 mol consumed; 1 mol remaining', MODEL_NOTE]) assert.ok(record.includes(text), text);
  assert.match(workedRecord(result), /Prediction: Not recorded/);
  assert.throws(() => workedRecord(result, 'guaranteed-yield'), /Unknown prediction/);
  assert.equal(outcomeText(solveReaction('water', ['0', '0'])), 'No product can form from these starting amounts.');
  assert.match(outcomeText(solveReaction('water', ['4', '2'])), /neither reactant remains/);
  assert.equal(formatMoles(2 / 3000), '0.00066666667');
  assert.equal(formatMoles(-0), '0');
  for (const invalid of [NaN, Infinity, -0.1]) assert.throws(() => formatMoles(invalid), /finite and nonnegative/);
});
