from pathlib import Path
import json,hashlib,datetime
r=Path('D:/HAMON/recallweave-diffusion-5f566b5ec8ef');p=r/'evidence/peer-mac';s=r/'source'
blind=json.loads((p/'blind-answers.json').read_text()); deck=json.loads((s/'courses/diffusion-stencil.json').read_text()); masked=json.loads((r/'evidence/course-questions-blind.json').read_text())
assert len(blind)==len(deck['items'])==12
for a,b,m in zip(blind,deck['items'],masked['items']):
 assert a['id']==b['id'] and a['answerIndex']==b['answer']
 assert {k:v for k,v in b.items() if k not in ('answer','explanation')}==m
report={'decision':'accepted','scope':'Independent exact model and original twelve-item course/guide; UI/browser/export lifecycle not reviewed here','time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'blindAnswersMatch':'12/12, with independently derived transfers retained before source exposure','model':'204 Fraction cases plus recursive immutability/detachment and39 strict refusals pass','contentFindings':['Periodic update uses the complete previous row, not an in-place sweep.','Mean and sum conservation follow the total coefficient per input, including signed data and ratios above one half.','Convex range and squared-deviation nonincrease are correctly qualified, with explicit non-strict endpoints zero and one half.','Alternating multiplier and examples at one quarter, one half, three quarters and one agree with independent derivations.','Constant preservation above the stability threshold is not presented as universal stability.','The finite eight-cell teaching scheme and approximate diagram are separated from PDE accuracy or physical temperature claims.'],'sourcePins':{x:hashlib.sha256((s/x).read_bytes()).hexdigest() for x in ['src/diffusion-stencil.mjs','courses/diffusion-stencil.json','courses/diffusion-stencil.md']},'evidencePins':{x:hashlib.sha256((p/x).read_bytes()).hexdigest() for x in ['blind-freeze.json','blind-answers.json','fraction-oracle.py','oracle-expected.json','compare-model.mjs','model-receipt.json']},'limits':'No owner tests read, no browser or learner suite replay; controls execute only frozen model. This is no claim of empirical learning benefit.'}
q=p/'independent-model-course-review.json';q.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print(json.dumps({'path':str(q),'sha256':hashlib.sha256(q.read_bytes()).hexdigest(),'sourcePins':report['sourcePins']}))
