from pathlib import Path
import json,hashlib,datetime
r=Path('D:/HAMON/recallweave-diffusion-5f566b5ec8ef');p=r/'evidence/peer-mac';e=r/'evidence'
names=['browser-fourth/lab-desktop.png','browser-fourth/lab-phone.png','browser-fourth/learner-phone.png','visual-final/default-phone-viewport.png','browser-fourth/receipt.json']
pins={x:hashlib.sha256((e/x).read_bytes()).hexdigest() for x in names}
receipt=json.loads((e/'browser-fourth/receipt.json').read_text());assert receipt['passed'] and receipt['source_unchanged'] and len(receipt['checks'])==9 and not receipt['page_errors'] and not receipt['requests']
assert hashlib.sha256((r/'source/courses/diffusion-stencil-lab.html').read_bytes()).hexdigest()=='07f944f4a7e95035bf1a41a1708453923d6fd326228d296f873ef0cfc0437a69'
report={'decision':'accepted final captures and phase-pinned receiver evidence','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':pins,'findings':['Actual default desktop shows the complete applied input beside the signed approximate profile, exact statistics and explicit initial-row explanation.','Default390px viewport keeps title, formula and labeled numeric draft controls legible within width.','Maximum24-step signed390px capture contains long fractions in wrapped statistics and intentionally horizontally scrollable tables. Receipt independently records documentwidth390/scrollwidth390 and SVG332; no page-level horizontal overflow is claimed from the screenshot alone.','The unchanged actual learner phone capture shows all12 original questions, first-attempt feedback, a separately labeled completed retry and authored reflection/study-note controls.','Current lab receipt nine groups passes, with byte-exact lesson/guide downloads, full applied observation, no requests/errors and unchanged source. Earlier two completed groups and harness-only failures remain separately retained as reported.'],'limits':'Read-only visual/receipt addendum. No browser/math rerun, synthesized interaction, product edit or assistive-technology certification. Narrow long tables require their existing horizontal scroll, as documented.','parentUISourceReviewSHA256':hashlib.sha256((p/'independent-ui-source-review.json').read_bytes()).hexdigest()}
q=p/'final-visual-addendum.json';q.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'path':str(q),'sha256':hashlib.sha256(q.read_bytes()).hexdigest(),'files':pins}))
