from pathlib import Path
import json,hashlib,re,datetime,ast
R=Path('D:/HAMON/recallweave-differentiation-5f566b5ec8ef');P=R/'evidence/peer-coordination';S=R/'source'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return p.read_bytes().decode('utf-8')
def j(p):return json.loads(read(p))
def write(name,value):(P/name).write_bytes((json.dumps(value,indent=2,ensure_ascii=False)+'\n').encode('utf-8'))
paths=['src/numerical-differentiation.mjs','src/numerical-differentiation-ui.mjs','courses/numerical-differentiation-lab.template.html','tools/build-numerical-differentiation.mjs','courses/numerical-differentiation.json','courses/numerical-differentiation.md','courses/numerical-differentiation-lab.html']
pins={p:{'sha256':sha(S/p),'bytes':(S/p).stat().st_size} for p in paths}
assert pins[paths[0]]['sha256']=='bf6a80c8b8bbfc2535629c9558aff92fd3c01dbc1cd49137eb16a03c0928fa56'
assert pins[paths[1]]['sha256']=='69622c6c6642494ed017523963872a63f42afc4af8741f4e180cec88796fc35e'
assert pins[paths[2]]['sha256']=='5d0107c0a2af1c0c9fae5220111b6658174f6c5e223f22e475d33f6ee4d8339c'
assert pins[paths[3]]['sha256']=='5ffab0606e6d4717937f473dea7299f8b700e499f3565d04fe80b9661c410f54'
model,ui,template,builder,course,guide,built=[read(S/p) for p in paths]
line="import { analyzeDifferentiation, serializeDifferentiation, DIFFERENCE_METHODS } from './numerical-differentiation.mjs';"
assert ui.startswith(line+'\n')
body=re.sub(r'^export (const|function) ',r'\1 ',model,flags=re.M)
code='const {analyzeDifferentiation,serializeDifferentiation,DIFFERENCE_METHODS}=(()=>{\n'+body+'\nreturn {analyzeDifferentiation,serializeDifferentiation,DIFFERENCE_METHODS};\n})();\n'+ui[len(line):]
result=template
for marker,value in [('/* COURSE_TEXT */',json.dumps(course,ensure_ascii=False).replace('<','\\u003c')),('/* GUIDE_TEXT */',json.dumps(guide,ensure_ascii=False).replace('<','\\u003c')),('/* MODEL_AND_UI */',code)]:
 assert result.count(marker)==1;result=result.replace(marker,value)
assert result.encode()==(S/'courses/numerical-differentiation-lab.html').read_bytes(),'Independent complete reconstruction'
process=j(P/'receiver-first-process.json');receipt=j(P/'model-course-receipt.json')
assert process['exit']==0 and receipt['cases']==346 and receipt['blindKeys']==12
common={'actor':'chatgpt:5f566b5ec8ef:coordination','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'decision':'accepted_in_reviewed_scope','sourcePins':pins,'ownerTestsReadOrRerun':False}
math={**common,'scope':'independent blind exact mathematics, strict input/export boundaries and original course/guide reasoning','freezeSHA256':sha(P/'blind-freeze.json'),'blindAnswersSHA256':sha(P/'blind-answers.json'),'oracleSHA256':sha(P/'fraction-oracle.py'),'expectedSHA256':sha(P/'oracle-expected.json'),'actualReceiptSHA256':sha(P/'model-course-receipt.json'),'actualProcess':process,'actualCounts':{k:receipt[k] for k in ['cases','levels','rules','rationalFields','serializedReports','invalidOrForgedRefusals','blindKeys']},'reasoning':['Every frozen rational sample, difference, divisor, estimate and signed/absolute error matched.','Degree guarantees remain separate from actual equality, including even symmetry and lucky coarse cancellation.','Central estimate can be worse than forward; finer h can leave exactness; the retained independent witnesses expose both.','All12 keys, complete masked prompts/options/transfers and guide worked responses match pre-source independent derivations.','Actual export keeps complete admitted record for each method, refuses copied/forged records; original input is detached and output recursively frozen.'],'referenceChecked':'NIST DLMF3.4, https://dlmf.nist.gov/3.4 ; independently expanded polynomial identities/oracle, no external exercise text copied.','limits':['No measured educational benefit, floating-point/noise model or optimal real-world step claim.','No browser or owner suite replay; visual/source reviews are separate.']}
write('independent-model-course-review.json',math)
ui_review={**common,'scope':'complete UI/template/builder read and independent exact built-byte reconstruction','independentBuiltBytes':len(result.encode()),'independentBuiltSHA256':hashlib.sha256(result.encode()).hexdigest(),'reasoning':['Input events immediately null current, clear/hide report and disable export; SELECT-only change handling avoids numeric blur retirement after Enter.','Preset fills a draft and retires; Calculate admits one complete set. Method changes inspect current only; failed admission hides stale content and keeps draft.','Secant line is anchored at the actual selected left sample with exact model slope converted only for display. Central line joins both endpoint samples, while tangent remains anchored at f(x).','Domain bounds keep approximate plot values finite; exact fractions and actual degree/error flags populate all tables. Approximate geometry is explicitly labeled.','Worked export serializes the current genuine report plus current method, including every refinement. Fixed course/guide text remains literal UTF8 bytes in separately generated Blob downloads.','Template tables are labeled keyboard regions with local horizontal scroll; narrow metrics wrap fractions.','Python reconstruction of all substitutions and exact model/UI closure equals the complete built HTML bytes without executing owner builder.'],'limits':['Source review and exact-byte reconstruction, not a new browser/learner run.']}
write('independent-ui-source-review.json',ui_review)
v1=j(R/'evidence/browser-v1/receipt.json');v3=j(R/'evidence/browser-v3-learner/receipt.json')
assert len(v1['checks'])==14 and len(v3['checks'])==6 and v3['exit']==0
for obj in [v1,v3]:
 assert not obj['errors'] and not obj['externalRequests']
 for p,entry in pins.items():assert obj['source'][p]==entry['sha256']
images=['browser-v1/lab-desktop.png','browser-v1/lab-phone.png','browser-v1/lab-phone-extreme.png','browser-v3-learner/learner-phone.png']
visual={**common,'scope':'direct read of actual owner captures and retained browser receipts; no browser replay','images':{p:{'sha256':sha(R/'evidence'/p),'bytes':(R/'evidence'/p).stat().st_size} for p in images},'receiptPins':{'labV1':sha(R/'evidence/browser-v1/receipt.json'),'learnerV3':sha(R/'evidence/browser-v3-learner/receipt.json')},'phaseAttribution':'Owner performed14 lab/download groups in first phase, then corrected receiver title/start assumptions. Separate final6 learner groups pass. Historical failed phases are not all-pass runs.','observations':['Desktop clearly distinguishes tangent and selected central secant and displays authoritative exact table values.','Default and extreme390px views retain controls and wrapped metrics; wide comparison tables scroll locally. Owner recorded390/390 document width.','Extreme signed quintic remains legible without claiming plot equality; long fraction wraps preserve underlying values.','Actual final learner image shows all12 first records, six retries, writing and explicit notes; no hidden score-efficacy inference.'],'limits':['Peer did not rerun browser or inspect user data.','Receipts and source pins bind these images; this is not a full canonical-tree publication proof.']}
write('independent-visual-review.json',visual)
ast.parse(read(P/'reproduce-expected.py'))
write('reproduction-note.json',{'nativeExpected':str(P/'oracle-expected.json'),'bytes':(P/'oracle-expected.json').stat().st_size,'sha256':sha(P/'oracle-expected.json'),'publicPacketPolicy':'Retain original bulk expected natively; copy generator, freeze/hash, receiver, all compact receipts and reproduction wrapper. No deletion.','command':'python reproduce-expected.py --output NEW_EXPECTED_FILE.json','wrapperStatus':'Source reviewed and AST parsed. It executes only the unchanged mathematical prefix and verifies exact expected hash before writing a new file; no duplicate bulk generation run claimed.'})
entries=[{'path':p.relative_to(P).as_posix(),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(P.rglob('*')) if p.is_file() and p.name not in ['oracle-expected.json','manifest.json']]
write('manifest.json',{'entries':entries,'omittedNativeBulk':{'path':'oracle-expected.json','sha256':sha(P/'oracle-expected.json'),'bytes':(P/'oracle-expected.json').stat().st_size},'notAFullCanonicalTreeReview':True})
print(json.dumps({'reviews':{n:sha(P/n) for n in ['independent-model-course-review.json','independent-ui-source-review.json','independent-visual-review.json','manifest.json']},'compactFiles':len(entries),'built':pins[paths[-1]]},indent=2))
