from pathlib import Path
import hashlib,json,shutil,datetime
r=Path(r'C:\Users\minec\hamon-recall-first-receiving-f3d1a0c556df')
out=r/'sealed-v1';out.mkdir(exist_ok=False)
entries=[]
for p in sorted(r.rglob('*')):
 if not p.is_file() or 'sealed-v1' in p.relative_to(r).parts or 'tmp' in p.relative_to(r).parts:continue
 rel=p.relative_to(r);dest=out/rel;dest.parent.mkdir(parents=True,exist_ok=True);data=p.read_bytes();dest.write_bytes(data)
 entries.append({'path':rel.as_posix(),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
v1=json.loads((r/'browser-v1'/'receipt.json').read_text(encoding='utf8'))
follow=json.loads((r/'browser-v1-bundled-followup'/'receipt.json').read_text(encoding='utf8'))
summary={'sealed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate_manifest':'178ffe6f72792159a9abbaba04bacdbcd24c4361a92e4021420193bd37c588fa','blind_freeze':'0afa02de387c11dc99c158d67ce816f19b4cb9bc06d5bf9c722f11e272b4db4c','original_groups':{'passed':v1['passed'],'total':v1['total'],'receipt_sha256':hashlib.sha256((r/'browser-v1'/'receipt.json').read_bytes()).hexdigest()},'bundled_followup':{'passed':follow['passed'],'total':follow['total'],'receipt_sha256':hashlib.sha256((r/'browser-v1-bundled-followup'/'receipt.json').read_bytes()).hexdigest()},'qualified_functional_groups':[1,2,3,4,5],'product_failure_group':6,'failure':'Admitted long title/prompt/concept overflows 390px viewport: preview1741px; prompt/revealed24606px. Credits and reference text wrap. Actual screenshots inspected.','preserved_infrastructure_interruption':'Original group1 stopped at Page.captureScreenshot protocol error; focused one-group followup passed after two requestAnimationFrame compositor synchronization. Original receipts/screenshots unchanged.','browser_only_limits':['Direct-file Chrome154.0.8037.98 in new isolated Playwright context; not user profile','Actual set_input_files, DOM keyboard/input and render checks; no human OS file-picker cancel qualification','Controlled stale-read test delays original File.arrayBuffer completion for own fixture names only; not OS disk scheduling','Rendered card hidden-reference study aid, not embedded source secrecy','No full canonical merge tree, screen-reader, production or provider validation'],'network_requests':v1['blocked_network_requests']+follow['blocked_network_requests'],'page_errors':v1['page_errors']+follow['page_errors'],'source_unchanged':v1['source_files_unchanged']==10 and follow['source_files_unchanged']==10,'owner_source_edits':0,'actions_started':0,'screenshots_inspected':['browser-v1/02-two-pass-preserved-history.png','browser-v1/06-long-preview-390.png','browser-v1/06-long-prompt-390.png','browser-v1/06-long-revealed-390.png','browser-v1-bundled-followup/01-bundled-before-reveal.png','browser-v1-bundled-followup/01-bundled-revealed.png']}
p=out/'SUMMARY.json';p.write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf8');b=p.read_bytes();entries.append({'path':'SUMMARY.json','bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()})
p=out/'MANIFEST.json';p.write_text(json.dumps({'files':entries},indent=2)+'\n',encoding='utf8')
print(json.dumps({'files':len(entries),'manifest_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'summary_sha256':hashlib.sha256((out/'SUMMARY.json').read_bytes()).hexdigest(),'network':summary['network_requests'],'page_errors':summary['page_errors']}))
