import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {validateDeck} from '../src/deck.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.resolve(process.argv[2] || path.join(root,'docs/receiving/momentum-collisions-0378a7b6/browser-'+Date.now()));
await fs.mkdir(out);
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const receipt={at:new Date().toISOString(),node:process.version,checks:[],downloads:[],source:{},errors:[],externalRequests:[],boundary:'Scripted offline product and existing-learner integration; not experimental physics or learning-effectiveness evidence.'};
const sourcePaths=['src/momentum-collisions.mjs','src/momentum-collisions-ui.mjs','templates/momentum-collisions-explorer.html','courses/momentum-collisions-explorer.html','courses/momentum-collisions.json','courses/momentum-collisions.md','tools/build-momentum-collisions.mjs','tools/check_momentum_collisions_browser.mjs','demo.html','src/deck.mjs','src/app.mjs'];
for(const name of sourcePaths)receipt.source[name]=sha(await fs.readFile(path.join(root,name)));
assert.equal(receipt.source['src/momentum-collisions.mjs'],'ba6e652a68b9018bb6ed59d671c43b04dfc4c617c0dc893c9f59a7197b8948cd');
const temp=path.join(out,'browser-temp');await fs.mkdir(temp);process.env.TEMP=temp;process.env.TMP=temp;
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--disable-background-networking','--disable-component-update','--no-first-run']});
 receipt.browser=browser.version();
 const context=await browser.newContext({offline:true,acceptDownloads:true,viewport:{width:1360,height:1100}});
 const page=await context.newPage();
 const watch=p=>{
  p.on('pageerror',error=>receipt.errors.push(error.message));
  p.on('console',entry=>{if(entry.type()==='error')receipt.errors.push(entry.text());});
  p.on('request',request=>{if(!/^(file:|data:|blob:)/.test(request.url()))receipt.externalRequests.push(request.url());});
 };
 watch(page);
 let observedDownloads=0;page.on('download',()=>observedDownloads++);
 const download=async(p,selector,name)=>{
  const pending=p.waitForEvent('download');await p.locator(selector).click();const item=await pending;
  assert.equal(await item.failure(),null);
  const target=path.join(out,name);await item.saveAs(target);
  const bytes=await fs.readFile(target);receipt.downloads.push({name,suggested:item.suggestedFilename(),sha256:sha(bytes),bytes:bytes.length});
  return target;
 };
 const exact=async(state,field)=>page.locator('[data-state="'+state+'"] [data-field="'+field+'"] strong').first().textContent();
 const total=async(state,field)=>page.locator('[data-state="'+state+'"] [data-field="'+field+'"]').textContent();
 const load=async id=>{await page.locator('#mc-preset').selectOption(id);await page.locator('#mc-load-example').click();};
 const setInputs=async values=>{for(const [name,value]of Object.entries(values))await page.locator('#mc-'+name).fill(value);await page.locator('#mc-compare').click();};
 const noOverflow=async p=>assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document horizontal overflow');
 await page.goto(pathToFileURL(path.join(root,'courses/momentum-collisions-explorer.html')).href);
 await page.locator('[data-state="elastic"]').waitFor();
 assert.equal(await exact('initial','a.velocity'),'3');
 assert.equal(await exact('elastic','a.velocity'),'1');assert.equal(await exact('elastic','b.velocity'),'4');
 assert.equal(await exact('completely-inelastic','a.velocity'),'2');
 assert.equal(await total('initial','totalMomentum'),'6 kg m/s');
 assert.equal(await total('elastic','totalKineticEnergy'),'9 J');
 assert.match(await total('completely-inelastic','kineticConverted'),/^3 J converted/);
 assert.equal(await page.locator('[data-velocity="initial-a"] line').getAttribute('x2'),'231');
 assert.equal(await page.locator('[data-velocity="elastic-b"] line').getAttribute('x2'),'258');
 assert.equal(await page.locator('[data-velocity="initial-b"] circle').getAttribute('cx'),'150');
 await noOverflow(page);
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 receipt.checks.push('Default live UI renders exact unequal-mass endpoint quantities and common-scale signed velocity glyphs.');
 const coursePath=await download(page,'#mc-download-course','download-course.json');
 const guidePath=await download(page,'#mc-download-guide','download-guide.md');
 assert.deepEqual(await fs.readFile(coursePath),await fs.readFile(path.join(root,'courses/momentum-collisions.json')));
 assert.deepEqual(await fs.readFile(guidePath),await fs.readFile(path.join(root,'courses/momentum-collisions.md')));
 const course=validateDeck(JSON.parse(await fs.readFile(coursePath,'utf8')));
 assert.equal(course.items.length,12);
 receipt.checks.push('Physically downloaded course and worked guide are byte-identical to validated original authored files.');
 const oldCount=observedDownloads;
 await page.locator('#mc-uA').fill('1e1');
 assert.equal(await page.locator('#mc-results').isVisible(),false);
 assert.equal(await page.locator('#mc-download-record').isDisabled(),true);
 await page.locator('#mc-compare').click();
 assert.equal(await page.locator('#mc-results').isVisible(),false);
 assert.equal(await page.locator('#mc-download-record').isDisabled(),true);
 assert.ok((await page.locator('#mc-status').textContent()).length>20);
 assert.equal(observedDownloads,oldCount);
 await load('unequal');
 await page.locator('#mc-uA').evaluate(node=>{node.value='4';});
 await page.locator('#mc-download-record').click();
 assert.equal(await page.locator('#mc-results').isVisible(),false);
 assert.equal(await page.locator('#mc-download-record').isDisabled(),true);
 assert.equal(observedDownloads,oldCount);
 receipt.checks.push('Dirty, invalid exponent, and programmatically changed inputs retire prior results and cannot download stale analysis.');
 await load('fractions');
 assert.equal(await exact('elastic','a.velocity'),'-7/3');assert.equal(await exact('elastic','b.velocity'),'5/3');
 assert.equal(await exact('completely-inelastic','a.velocity'),'1/3');
 assert.equal(await page.locator('#mc-center-energy').textContent(),'1/6');
 assert.equal(await page.locator('#mc-relative-energy').textContent(),'16/3');
 assert.equal(await page.locator('[data-velocity="elastic-a"] line').getAttribute('x2'),'66');
 assert.equal(await page.locator('[data-velocity="elastic-b"] line').getAttribute('x2'),'210');
 const fractionPath=await download(page,'#mc-download-record','fraction-analysis.json');
 const fraction=JSON.parse(await fs.readFile(fractionPath,'utf8'));
 assert.deepEqual(fraction.inputs,{mA:1,mB:2,uA:3,uB:-1});
 assert.deepEqual(fraction.elastic.a.velocity,{numerator:'-7',denominator:'3'});
 assert.deepEqual(fraction.completelyInelastic.kineticConverted,{numerator:'16',denominator:'3'});
 receipt.checks.push('Fractional signed quantities and arrow coordinates agree with a hand-derived case; actual downloaded record binds those inputs and reduced fractions.');
 for(const id of ['equal-speed','separating']){
  await load(id);assert.equal(await page.locator('[data-state]').count(),1);
  assert.match(await page.locator('#mc-results-title').textContent(),/No future collision/);
  assert.match(await page.locator('#mc-event-boundary').textContent(),/endpoints are not calculated/);
  const record=JSON.parse(await fs.readFile(await download(page,'#mc-download-record',id+'-analysis.json'),'utf8'));
  assert.equal(record.status,'no-collision');assert.equal(record.elastic,null);assert.equal(record.completelyInelastic,null);
 }
 await load('both-left');
 assert.equal(await page.locator('[data-state]').count(),3);
 assert.match(await page.locator('#mc-event-boundary').textContent(),/gap closes/);
 assert.equal(await exact('elastic','a.velocity'),'-7/3');
 assert.equal(await exact('elastic','b.velocity'),'-1/3');
 receipt.checks.push('Equal/receding pairs show one initial state and null endpoint downloads; both-left approaching pair remains a valid event.');
 await setInputs({mA:'100',mB:'1',uA:'20',uB:'-20'});
 assert.equal(await page.locator('[data-state]').count(),3);
 const svgEnds=await page.locator('[data-velocity] line').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('x2'))));
 assert.ok(svgEnds.every(x=>x>=42&&x<=258));
 assert.ok(await page.locator('#mc-download-record').isEnabled());
 await noOverflow(page);
 const beforeError=observedDownloads;
 await page.evaluate(()=>{window.restoreCreateObjectURL=URL.createObjectURL;URL.createObjectURL=()=>{throw new Error('receiving download refusal');};});
 await page.locator('#mc-download-record').click();
 assert.match(await page.locator('#mc-download-status').textContent(),/could not be prepared/);
 assert.equal(observedDownloads,beforeError);
 assert.equal(await page.locator('#mc-results').isVisible(),true);
 await page.evaluate(()=>{URL.createObjectURL=window.restoreCreateObjectURL;delete window.restoreCreateObjectURL;});
 await load('zero-momentum');
 assert.equal(await total('initial','totalMomentum'),'0 kg m/s');
 assert.equal(await total('initial','totalKineticEnergy'),'9 J');
 assert.equal(await exact('completely-inelastic','a.velocity'),'0');
 receipt.checks.push('Extreme allowed masses/velocities stay within the common diagram scale; download preparation failure reports honestly and the page recovers.');

 await page.setViewportSize({width:390,height:844});
 await page.locator('#mc-preset').selectOption('fractions');
 await page.locator('#mc-load-example').focus();await page.keyboard.press('Enter');
 assert.equal(await exact('elastic','a.velocity'),'-7/3');
 await noOverflow(page);
 await page.locator('#mc-mA').focus();
 for(const name of ['uA','mB','uB']){
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'mc-'+name);
 }
 await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'mc-compare');
 await page.keyboard.press('Enter');
 assert.equal(await exact('completely-inelastic','a.velocity'),'1/3');
 await page.screenshot({path:path.join(out,'phone.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>localStorage.length),0);
 assert.equal(await page.evaluate(()=>sessionStorage.length),0);
 assert.deepEqual(await context.cookies(),[]);
 receipt.checks.push('390px layout has no horizontal overflow; labeled cart fields and Compare are reachable and operable by keyboard; explorer writes no browser storage.');

 const learner=await context.newPage();watch(learner);
 await learner.goto(pathToFileURL(path.join(root,'demo.html')).href);
 await learner.locator('#deck-file').setInputFiles(coursePath);
 await learner.locator('#start-deck').waitFor();
 assert.equal(await learner.locator('#deck-preview-title').textContent(),course.title);
 assert.match(await learner.locator('.deck-preview-count').textContent(),/12 questions/);
 assert.equal(await learner.locator('.question-card').count(),0);
 await learner.locator('#start-deck').click();
 const asked=new Set();let missed;
 for(let index=0;index<12;index++){
  const prompt=await learner.locator('.question-card h2').textContent();
  const item=course.items.find(value=>value.prompt===prompt);assert.ok(item,'real learner prompt belongs to course');
  assert.ok(!asked.has(item.id));asked.add(item.id);
  const choice=index===0?(item.answer+1)%item.options.length:item.answer;
  if(index===0)missed={item,choice};
  await learner.locator('[data-choice="'+choice+'"]').click();
  const feedback=await learner.locator('#feedback-slot').textContent();
  assert.ok(feedback.includes(item.explanation),item.id+' explanation');
  assert.ok(feedback.includes(item.transfer),item.id+' transfer');
  assert.equal(await learner.locator('#step-count').textContent(),(index+1)+' / 12');
  await learner.locator('#next-button').click();
 }
 assert.equal(asked.size,12);assert.equal(await learner.locator('.review-item').count(),12);
 assert.match(await learner.locator('#first-try-summary').textContent(),/11 of 12/);
 const missedReview=learner.locator('.review-item').filter({has:learner.locator('[data-reflection-item="'+missed.item.id+'"]')});
 await missedReview.locator('summary').click();
 assert.ok((await missedReview.textContent()).includes(missed.item.options[missed.choice]));
 assert.ok((await missedReview.textContent()).includes(missed.item.options[missed.item.answer]));
 const note='Scripted receiving note: signed momentum <does not> square the velocity; μ is positive.';
 await learner.locator('[data-reflection-item="'+missed.item.id+'"]').fill(note);
 const application='Scripted transfer check: I must test the positive gap before applying collision endpoints.';
 await learner.locator('#application-reflection').fill(application);
 await learner.locator('#practice-button').click();
 assert.equal(await learner.locator('.practice-card h2').textContent(),missed.item.prompt);
 await learner.locator('[data-practice-choice="'+missed.item.answer+'"]').click();
 assert.ok((await learner.locator('#practice-feedback').textContent()).includes(missed.item.explanation));
 await learner.locator('#practice-next').click();
 assert.match(await learner.locator('#first-try-summary').textContent(),/11 of 12/);
 assert.match(await learner.locator('#practice-status').textContent(),/1 of 1 correctly on retry/);
 const notesPath=await download(learner,'#save-notes-button','download-study-notes.txt');
 const notes=await fs.readFile(notesPath,'utf8');
 for(const item of course.items){
  for(const expected of [item.prompt,item.options[item.answer],item.explanation,item.transfer])
   assert.ok(notes.includes(expected),'notes preserve '+item.id);
 }
 assert.ok(notes.includes(note));assert.ok(notes.includes(application));
 assert.ok(notes.includes(missed.item.options[missed.choice]));
 assert.match(notes,/Practice|practice/);
 assert.match(notes,/11 of 12|11\/12/);
 await noOverflow(learner);
 await learner.screenshot({path:path.join(out,'learner-trace.png'),fullPage:true});
 receipt.courseOrder=[...asked];receipt.scriptedFirstMiss={id:missed.item.id,choice:missed.choice,correct:missed.item.answer};
 receipt.checks.push('Actual downloaded JSON enters the unchanged learner through preview and explicit start; all twelve unique questions expose their authored feedback and transfer prompts.');
 receipt.checks.push('One deliberate first-answer mistake survives separate successful retry; physically downloaded notes preserve every prompt, correct answer, explanation, transfer, first mistake and literal typed reflections.');
 assert.deepEqual(receipt.errors,[]);assert.deepEqual(receipt.externalRequests,[]);
 for(const [name,hash]of Object.entries(receipt.source))assert.equal(sha(await fs.readFile(path.join(root,name))),hash,'frozen source '+name);
 const original=JSON.parse(await fs.readFile(path.join(root,'docs/receiving/momentum-collisions-0378a7b6/baseline/original-source-native.json'),'utf8'));
 for(const entry of original)assert.equal(sha(await fs.readFile(path.join(root,entry.path))),entry.native_sha256,entry.path);
 receipt.originalNativeLeavesPreserved=original.length;
 receipt.checks.push('All 2084 original native leaves and all frozen source inputs remain unchanged; zero observed runtime errors and external requests.');
 receipt.passed=true;
 await browser.close();browser=null;await fs.rm(temp,{recursive:true,force:true});
}catch(error){receipt.passed=false;receipt.failure=error.stack;process.exitCode=1;}
finally{
 if(browser)await browser.close();
 await fs.writeFile(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');
 console.log(JSON.stringify(receipt,null,2));
}
