import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const root = new URL('../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');
function replaceOnce(source, from, to, name) {
  if (source.split(from).length !== 2) throw new Error(`Expected one ${name} marker.`);
  return source.replace(from, () => to);
}
function safeScript(source) {
  return source.replace(/<\/script/gi, '<\\/script');
}
const core = replaceOnce(read('src/stable-sorting.mjs'),
  'export { buildSortingComparison, parseSortingKey };', '', 'core export');
const course = read('courses/stable-sorting.json');
const literalCourse = JSON.stringify(course).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
let app = replaceOnce(read('stable-sorting/app.mjs'),
  "import {buildSortingComparison, parseSortingKey} from '../src/stable-sorting.mjs';", '', 'module import');
const loader = app.match(/\/\/ LESSON_LOADER_START\n[\s\S]*?\/\/ LESSON_LOADER_END/);
if (!loader) throw new Error('Expected one complete lesson loader.');
app = replaceOnce(app, loader[0],
  `const embeddedLessonText = ${literalCourse};\nasync function loadLessonText() { return embeddedLessonText; }`,
  'lesson loader');
let html = replaceOnce(read('stable-sorting/index.html'),
  '<link rel="stylesheet" href="./styles.css">', `<style>\n${read('stable-sorting/styles.css')}</style>`, 'stylesheet');
html = replaceOnce(html, '<script type="module" src="./app.mjs"></script>',
  `<script type="module">\n${safeScript(core + '\n' + app)}</script>`, 'module script');
html = replaceOnce(html, 'href="../demo.html"', 'href="demo.html"', 'learner path');
html = replaceOnce(html, '<!doctype html>',
  '<!doctype html>\n<!-- Generated by tools/make_stable_sorting.mjs; edit the modular source. -->', 'doctype');
const destination = new URL('stable-sorting.html', root);
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== html) {
    process.stderr.write('stable-sorting.html is out of date. Run node tools/make_stable_sorting.mjs.\n');
    process.exitCode = 1;
  } else process.stdout.write('Stable-sorting standalone parity passed.\n');
} else {
  writeFileSync(destination, html);
  process.stdout.write(`Built ${fileURLToPath(destination)} (${Buffer.byteLength(html)} bytes).\n`);
}
